# Example: Generate credentials and store in Vault
#
# Prerequisites:
# - A KVMount must exist for the namespace (platform/<namespace>/kv)
# - A SecretStore named <namespace>-secret-store must exist
#
# Expected secret output (gitea-templated-userpass:
# data.credentials
apiVersion: secrets.platform.lab/v1alpha1
kind: UserPass
metadata:
  name: gitea-templated-userpass
  namespace: crossplane-examples
spec:
  username: test-abc
  length: 32
  includeSymbols: false
  outputTemplate:
    onlyTemplate: true
    secretKey: credentials
    values:
      base_url: http://gitea-http.gitea.svc.cluster.local:3000
    template: '{"base_url":"{{ .base_url }}","username":"{{ .username }}","password":"{{ .password }}"}'
---
# Expected secret output (gitea-test-user):
# data.username
# data.password
apiVersion: secrets.platform.lab/v1alpha1
kind: UserPass
metadata:
  name: gitea-test-user
  namespace: crossplane-examples
spec:
  username: test-123
