# Example: Namespace Onboarding (one-time resources)
#
# This file groups the one-time resources needed before using higher-level
# compositions like Random and UserPass in a namespace.
#
# Creates:
# 1) KVMount at platform/<namespace>/kv
# 2) ServiceAccount used by SecretStore Kubernetes auth
# 3) SecretStore bound to namespace KV path
# 4) Vault Policy scoped to namespace KVv2 path
# 5) Vault AuthRole binding namespace SA -> namespace policy
---
apiVersion: secrets.platform.lab/v1alpha1
kind: KVMount
metadata:
  name: kv-mount
  namespace: crossplane-examples
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: crossplane-examples
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: crossplane-examples-secret-store
  namespace: crossplane-examples
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "platform/crossplane-examples/kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "crossplane-examples-auth"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "crossplane-examples"
---
apiVersion: secrets.platform.lab/v1alpha1
kind: Policy
metadata:
  name: crossplane-examples-kv-policy
  namespace: crossplane-examples
spec:
  accessMode: readwrite
  engines:
    - kv
---
apiVersion: secrets.platform.lab/v1alpha1
kind: AuthRole
metadata:
  name: crossplane-examples-auth
  namespace: crossplane-examples
spec:
  backend: kubernetes
  roleName: crossplane-examples-auth
  boundServiceAccountNames:
    - external-secrets
  policyNames:
    - crossplane-examples-kv-policy
  tokenTtl: 3600
