apiVersion: v2
name: cert-manager
description: Wrapper chart to deploy cert-manager and bootstrap the platform root CA and ClusterIssuers.
version: 0.1.0
dependencies:
  - name: cert-manager
    version: "1.19.2"
    repository: "https://charts.jetstack.io"
