apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-vault
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-token-reader
  namespace: vault
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  resourceNames: ["crossplane-token"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provider-vault-crossplane-token-reader
  namespace: vault
subjects:
- kind: ServiceAccount
  name: provider-vault
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: crossplane-token-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-vault-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-vault
          containers:
            - name: package-runtime
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-vault
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/upbound/provider-vault:v3.0.3
  runtimeConfigRef:
    name: provider-vault-runtime-config
