# Example: Request a PostgreSQL database for your application
#
# Prerequisites:
# - Vault onboarding resources must exist in the namespace:
#   KVMount, ServiceAccount, SecretStore, Policy, AuthRole
#   (see example-claims/secrets/vault-onboarding-claim.yaml)
#
# This claim creates:
# - A UserPass claim that generates credentials and stores them in Vault
# - A <databaseName>-db secret with keys: username, password, uri
# - A single-instance CloudNative-PG cluster in your namespace
#
# Usage in your application:
#   env:
#     - name: DATABASE_URL
#       valueFrom:
#         secretKeyRef:
#           name: <databaseName>-db
#           key: uri
#
# Note:
# - The uri value URL-encodes the password (for example, @ becomes %40).
# - Pass uri directly to a PostgreSQL client/driver as DATABASE_URL.
#   The driver decodes it during connection parsing.

# Minimal example (uses all defaults):
apiVersion: storage.platform.lab/v1alpha1
kind: Postgres
metadata:
  name: myapp-db
  namespace: crossplane-examples
spec:
  databaseName: myapp
---
# Full example with all options:
apiVersion: storage.platform.lab/v1alpha1
kind: Postgres
metadata:
  name: myapp-db-full
  namespace: crossplane-examples
spec:
  # Required: Name of the database (also used for username)
  databaseName: myapp-full

  # Optional: Persistent volume size (default: 1Gi)
  storageSize: "5Gi"

  # Optional: Resource limits
  resources:
    cpu: "1"
    memory: "1Gi"
