# Example: Request a PostgreSQL database for your application
#
# This claim creates:
# - A single-instance CloudNative-PG cluster in your namespace
# - A secure password stored in Vault at platform/database/<databaseName>
# - An ExternalSecret that syncs credentials to your namespace as <databaseName>-db
#
# Usage in your application:
#   - Mount the secret <databaseName>-db with keys: host, port, username, password, database, uri
#   - Or use environment variables from the secret
#
# Minimal example (uses all defaults):
apiVersion: database.platform.local/v1alpha1
kind: PostgresDatabase
metadata:
  name: myapp-db
  namespace: myapp
spec:
  databaseName: myapp

---
# Full example with all options:
apiVersion: database.platform.local/v1alpha1
kind: PostgresDatabase
metadata:
  name: myapp-db-full
  namespace: myapp
spec:
  # Required: Name of the database (also used for username)
  databaseName: myapp

  # Optional: Persistent volume size
  # Default: 1Gi
  storageSize: "5Gi"

  # Optional: PostgreSQL major version
  # Default: "17"
  postgresVersion: "16"

  # Optional: Resource limits
  resources:
    cpu: "1"
    memory: "1Gi"

  # Optional: Enable PgBouncer connection pooler
  # Default: false
  enablePooler: true

  # Connection secret will be written to: myapp-db-full-connection-secret
  writeConnectionSecretToRef:
    name: myapp-db-full-connection-secret
