# Example: Create an app repository under homelab org
apiVersion: registry.local.lab/v1alpha1
kind: Repo
metadata:
  name: demo-split
  namespace: crossplane-examples
spec:
  registryHost: git.local.lab
  orgName: homelab
  description: "Container registry for demo-split"
  private: true
