apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-gitea
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provider-gitea-token-reader
  namespace: gitea
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["crossplane-gitea-provider-token"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provider-gitea-token-reader
  namespace: gitea
subjects:
  - kind: ServiceAccount
    name: provider-gitea
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: provider-gitea-token-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gitea-runtime-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-gitea
          containers:
            - name: package-runtime
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gitea
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: ghcr.io/0xayf/provider-upjet-gitea:v0.1.4
  runtimeConfigRef:
    name: provider-gitea-runtime-config
---
apiVersion: gitea.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: gitea-provider-config
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: gitea
      name: crossplane-gitea-provider-token
      key: credentials
