apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: randoms.secrets.platform.lab
spec:
  group: secrets.platform.lab
  names:
    kind: Random
    plural: randoms
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                length:
                  type: integer
                  description: Length of the generated password
                  default: 32
                  minimum: 16
                  maximum: 128
                includeSymbols:
                  type: boolean
                  description: Include special characters in the password
                  default: false
            status:
              type: object
              properties:
                vaultPath:
                  type: string
                  description: Full path to the secret in Vault
                ready:
                  type: boolean
                  description: Whether the secret is ready in Vault
