apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: kvmounts.secrets.platform.lab
spec:
  group: secrets.platform.lab
  names:
    kind: KVMount
    plural: kvmounts
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
                  description: Human-readable description of the KV engine
                  default: "KV v2 secrets engine managed by Crossplane"
            status:
              type: object
              properties:
                mountPath:
                  type: string
                  description: The full Vault mount path
