---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shared-gateway-wildcard
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: {{ .Values.sharedGateway.tls.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificates.clusterIssuer }}
  dnsNames: {{ .Values.sharedGateway.tls.dnsNames | toJson }}
