---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitea-admin-push
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  updatePolicy: Replace
  secretStoreRefs:
    - name: gitea-secret-store
      kind: SecretStore
  selector:
    secret:
      name: gitea-admin
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: gitea-admin
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: gitea-admin
          property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitea-secret-store
    kind: SecretStore
  target:
    name: gitea-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ "{{ .username }}" }}"
        password: "{{ "{{ .password }}" }}"
  data:
    - secretKey: username
      remoteRef:
        key: gitea-admin
        property: username
    - secretKey: password
      remoteRef:
        key: gitea-admin
        property: password
