---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    local.lab/oidc-consumer: "true"
    local.lab/shared-gateway-access: "true"
