---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-platform-root-ca-reader
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - platform-root-ca
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-platform-root-ca-reader
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-platform-root-ca-reader
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "{{ .Release.Namespace }}-k8s-secret-store"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: "{{ .Release.Namespace }}"
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: "{{ .Release.Namespace }}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-keycloak-client-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.keycloak.clientSecret
      remoteRef:
        key: argocd-oidc-client-secret
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-keycloak-root-ca
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "11"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Release.Namespace }}-k8s-secret-store"
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.keycloak.rootCA
      remoteRef:
        key: platform-root-ca
        property: ca.crt
