{{- $breakglassAdmin := .Values.bootstrap.breakglassAdmin | default dict -}}
{{- $breakglassAdminUsername := required "bootstrap.breakglassAdmin.username is required" $breakglassAdmin.username -}}
{{- $labAdmin := .Values.bootstrap.labAdmin -}}
---
apiVersion: secrets.local.lab/v1alpha1
kind: UserPass
metadata:
  name: "{{ $breakglassAdminUsername }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: "{{ $breakglassAdminUsername }}"
  length: 48
  includeSymbols: true
---
apiVersion: secrets.local.lab/v1alpha1
kind: UserPass
metadata:
  name: "{{ $labAdmin.username }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: "{{ $labAdmin.username }}"
  length: 48
  includeSymbols: true
---
apiVersion: secrets.local.lab/v1alpha1
kind: UserPass
metadata:
  name: crossplane-keycloak-provider-credentials
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: "{{ .Values.crossplaneProvider.username }}"
  length: 48
  includeSymbols: true
  outputTemplate:
    onlyTemplate: true
    secretKey: credentials
    values:
      url: http://{{ .Release.Name }}-http.{{ .Release.Namespace }}.svc.cluster.local
      base_path: ""
      realm: master
      client_id: admin-cli
    template: |
      {
        "url": "{{ `{{ .url }}` }}",
        "base_path": "{{ `{{ .base_path }}` }}",
        "realm": "{{ `{{ .realm }}` }}",
        "client_id": "{{ `{{ .client_id }}` }}",
        "username": "{{ `{{ .username }}` }}",
        "password": "{{ `{{ .password }}` }}"
      }
