apiVersion: secrets.platform.lab/v1alpha1
kind: Policy
metadata:
  name: external-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  policyDocument: |
    path "platform/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    path "platform/data/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    path "platform/metadata/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
---
apiVersion: secrets.platform.lab/v1alpha1
kind: AuthRole
metadata:
  name: external-secrets-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  backend: kubernetes
  roleName: external-secrets
  boundServiceAccountNames:
    - external-secrets
  boundServiceAccountNamespaces:
    - "*"
  policyNames:
    - external-secrets
  tokenTtl: 3600
