vault:
  # Configure the server to run in a single-replica, standalone mode
  server:
    standalone:
      enabled: true
    ha:
      enabled: false  
    dataStorage:
      enabled: true
      size: 1Gi
      storageClass: __DEFAULT_STORAGE_CLASS__
  
  injector:
    enabled: false

  ui:
    enabled: true
    ingress:
      hostname: __VAULT_HOSTNAME__
