apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: policies.secrets.platform.lab
spec:
  group: secrets.platform.lab
  names:
    kind: Policy
    plural: policies
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                accessMode:
                  type: string
                  description: Access mode for generated policy rules.
                  default: readwrite
                  enum:
                    - read
                    - readwrite
                engines:
                  type: array
                  description: Secret engines to include in policy generation.
                  items:
                    type: string
                  default:
                    - kv
                policyDocument:
                  type: string
                  description: Optional raw Vault policy document. If set, this is used as-is and generated engine rules are ignored.
            status:
              type: object
              properties:
                policyName:
                  type: string
                  description: Vault policy name.
