apiVersion: secrets.local.lab/v1alpha1
kind: UserPass
metadata:
  name: root-credentials
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  username: rustfs-admin
  length: 48
  includeSymbols: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-root-credentials
  namespace: "{{ .Release.Namespace }}"
  annotations:
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore
  target:
    name: rustfs-root-credentials
    creationPolicy: Owner
    template:
      data:
        RUSTFS_ACCESS_KEY: |-
          {{ "{{ .username }}" }}
        RUSTFS_SECRET_KEY: |-
          {{ "{{ .password }}" }}
  data:
    - secretKey: username
      remoteRef:
        key: root-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: root-credentials
        property: password
