---
apiVersion: secrets.local.lab/v1alpha1
kind: Random
metadata:
  name: {{ .Values.cookieSecretName }}
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 32
  includeSymbols: false
