---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-runtime
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Release.Namespace }}-secret-store"
    kind: SecretStore
  target:
    name: {{ .Values.runtimeSecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        client-id: {{ .Values.oidc.clientId | quote }}
  data:
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.clientSecretName }}
        property: password
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.cookieSecretName }}
        property: password
