apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgres.storage.platform.lab
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    crossplane.io/xrd: postgres.storage.platform.lab
spec:
  compositeTypeRef:
    apiVersion: storage.platform.lab/v1alpha1
    kind: Postgres
  mode: Pipeline
  pipeline:
    - step: render-postgres
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := getCompositeResource . -}}
            {{- $namespace := $xr.metadata.namespace -}}
            {{- $name := $xr.metadata.name -}}
            {{- $databaseName := $xr.spec.databaseName -}}
            {{- $storageSize := default "1Gi" $xr.spec.storageSize -}}
            {{- $resources := default dict $xr.spec.resources -}}
            {{- $cpuLimit := default "500m" $resources.cpu -}}
            {{- $memoryLimit := default "512Mi" $resources.memory -}}
            {{- $clusterName := printf "pg-%s" $databaseName -}}
            {{- $secretName := printf "%s-db" $databaseName -}}
            {{- $primaryHost := printf "%s-rw.%s.svc.cluster.local" $clusterName $namespace -}}
            ---
            {{/* Create UserPass claim — delegates password generation and Vault storage */}}
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: userpass-claim
            spec:
              forProvider:
                manifest:
                  apiVersion: secrets.platform.lab/v1alpha1
                  kind: UserPass
                  metadata:
                    name: {{ $secretName }}
                    namespace: {{ $namespace }}
                  spec:
                    username: {{ $databaseName }}
                    length: 48
                    includeSymbols: true
                    outputTemplate:
                      onlyTemplate: false
                      secretKey: uri
                      values:
                        host: {{ $primaryHost }}
                        port: "5432"
                        database: {{ $databaseName }}
                      template: {{ `'postgresql://{{ .username }}:{{ .password | urlquery }}@{{ .host }}:{{ .port }}/{{ .database }}'` }}
              readiness:
                policy: DeriveFromObject
              providerConfigRef:
                kind: ClusterProviderConfig
                name: provider-kubernetes-config
            ---
            {{/* Create CloudNative-PG Cluster */}}
            apiVersion: kubernetes.m.crossplane.io/v1alpha1
            kind: Object
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: cnpg-cluster
            spec:
              forProvider:
                manifest:
                  apiVersion: postgresql.cnpg.io/v1
                  kind: Cluster
                  metadata:
                    name: {{ $clusterName }}
                    namespace: {{ $namespace }}
                  spec:
                    instances: 1
                    imageName: ghcr.io/cloudnative-pg/postgresql:18
                    bootstrap:
                      initdb:
                        database: {{ $databaseName }}
                        owner: {{ $databaseName }}
                        secret:
                          name: {{ $secretName }}
                    storage:
                      size: {{ $storageSize }}
                      storageClass: local-path
                    resources:
                      limits:
                        cpu: {{ $cpuLimit | quote }}
                        memory: {{ $memoryLimit | quote }}
                      requests:
                        cpu: "100m"
                        memory: "256Mi"
                    monitoring:
                      enablePodMonitor: false
              readiness:
                policy: DeriveFromObject
              providerConfigRef:
                kind: ClusterProviderConfig
                name: provider-kubernetes-config
              references:
                - dependsOn:
                    apiVersion: v1
                    kind: Secret
                    namespace: {{ $namespace }}
                    name: {{ $secretName }}
            ---
            apiVersion: storage.platform.lab/v1alpha1
            kind: Postgres
            metadata:
              name: {{ $xr.metadata.name }}
            status:
              clusterName: {{ $clusterName }}
              primaryHost: {{ $primaryHost }}
              ready: true
    - step: auto-ready
      functionRef:
        name: function-auto-ready
