apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-vault
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-token-reader
  namespace: vault
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  resourceNames: ["crossplane-token"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provider-vault-crossplane-token-reader
  namespace: vault
subjects:
- kind: ServiceAccount
  name: provider-vault
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: crossplane-token-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-vault-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-vault
          containers:
            - name: package-runtime
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-vault
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/health.lua: |
      hs = {}
      hs.status = "Progressing"
      hs.message = "Waiting for Installed and Healthy conditions"
      local installed = false
      local healthy = false
      if obj.status and obj.status.conditions then
        for _, c in ipairs(obj.status.conditions) do
          if c.type == "Installed" then installed = (c.status == "True") end
          if c.type == "Healthy" then healthy = (c.status == "True") end
        end
        if installed and healthy then
          hs.status = "Healthy"
          hs.message = "Provider installed and healthy"
        else
          hs.status = "Progressing"
          hs.message = "installed=" .. tostring(installed) .. ", healthy=" .. tostring(healthy)
        end
      end
      return hs
spec:
  package: xpkg.upbound.io/upbound/provider-vault:v2.2.1
  runtimeConfigRef:
    name: provider-vault-runtime-config
