apiVersion: v2
name: cloudnative-pg
description: A wrapper chart to deploy the CloudNativePG operator.
version: 0.1.0
dependencies:
  - name: cloudnative-pg
    version: "0.24.0"
    repository: "https://cloudnative-pg.github.io/charts"