# Example KVMount - creates a Vault KV v2 engine at platform/<namespace>/kv
# Deploy this in any namespace to create a KV engine for that namespace
#
# This will create a KV engine at: platform/crossplane-examples/kv
apiVersion: secrets.platform.lab/v1alpha1
kind: KVMount
metadata:
  name: kv-mount
  namespace: crossplane-examples
spec: {}
---
# ClusterSecretStore for external-secrets to access namespace's KV mount
#
# Prerequisites:
# - A KVMount must exist for the namespace (creates platform/<namespace>/kv)
#
# This creates a ClusterSecretStore that points to the namespace's KV mount,
# allowing Random secrets to push/pull from Vault.
#
# Naming convention: <namespace>-secret-store
# This must match what the Random composition expects.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: crossplane-examples-secret-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "platform/crossplane-examples/kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
