# Example: Generate a random secret and stores it in Vault
#
# Prerequisites:
# - A KVMount must exist for the namespace (platform/<namespace>/kv)
#
# This creates:
# - A random password stored in Vault at platform/<namespace>/kv/<name>
# - A Kubernetes Secret in the same namespace with the password
#
# The secret name in Vault and K8s is derived from metadata.name
# The mount path is derived from metadata.namespace
apiVersion: secrets.platform.lab/v1alpha1
kind: Random
metadata:
  name: api-key
  namespace: crossplane-examples
spec: {}
---
# Example with custom options:
apiVersion: secrets.platform.lab/v1alpha1
kind: Random
metadata:
  name: api-key-custom
  namespace: crossplane-examples
spec:
  # Password length (16-128 characters, default: 32)
  length: 64
  # Include special characters (default: false)
  includeSymbols: true
